#!/sbin/busybox sh
#made by Anomalchik and DerTeufel
BB=/sbin/busybox
cd /

$BB mkdir /tmp
$BB mount -t tmpfs tmpfs /tmp
$BB mount -t proc proc /proc
$BB sed -e 's/fps\=5893/fps\=5893 androidboot\.selinux\=permissive/' /proc/cmdline > /tmp/cmdline

$BB mount --bind -o ro /tmp/cmdline /proc/cmdline

$BB chmod 755 /init2
$BB mv /init2 /init
exec /init

